cloudquery/plugin-sdk-java

.github/.kodiak.toml
.github/renovate.json5
.github/workflows/pr_title.yml
.github/workflows/publish.yml
.github/workflows/release_pr.yml
lib/build.gradle
lib/src/main/java/io/cloudquery/internal/servers/discovery/v1/DiscoverServer.java
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java

Similar release flow to https://github.com/cloudquery/plugin-pb-java, plus dependency updates, plus `automerge` for PRs plus updating to latest `io.cloudquery` pb jar

chore: Add Kodiak, Renovate, Update pb jar

---

lib/build.gradle
lib/src/main/java/io/cloudquery/helper/GlobMatcher.java
lib/src/main/java/io/cloudquery/schema/SchemaException.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/test/java/io/cloudquery/helper/GlobMatcherTest.java
lib/src/test/java/io/cloudquery/schema/TableFilterDFSTest.java
lib/src/test/java/io/cloudquery/schema/TableFlattenTest.java
lib/src/test/java/io/cloudquery/schema/TableMaxTest.java

Implementing the same tests as we have in the Go [plugin-sdk](https://github.com/cloudquery/plugin-sdk/blob/main/schema/table_test.go#L58-L276) supporting filtering tables by including and skipping tables based on glob patterns.

feat: adding Table filterDFS functionaility

---

lib/src/main/java/io/cloudquery/scalar/Bool.java
lib/src/test/java/io/cloudquery/scalar/BinaryTest.java
lib/src/test/java/io/cloudquery/scalar/BoolTest.java
lib/src/test/java/io/cloudquery/scalar/LargeBinaryTest.java

feat: `io.cloudquery.scalar.Bool`

---

lib/src/main/java/io/cloudquery/caser/Caser.java
lib/src/main/java/io/cloudquery/caser/Initialisms.java
lib/src/test/java/io/cloudquery/caser/CaserTest.java

Adding caser implementation to support transformer development
A port of the Go [caser](https://github.com/cloudquery/plugin-sdk/tree/main/caser) package.

chore: adding caser implementation

---

lib/src/main/java/io/cloudquery/transformers/NameTransformer.java
lib/src/test/java/io/cloudquery/transformers/DefaultNameTransformerTest.java

fixes: https://github.com/cloudquery/plugin-sdk-java/issues/29

chore: adding NameTransformer interface and default implementation

---

lib/src/main/java/io/cloudquery/transformers/NameTransformer.java
lib/src/main/java/io/cloudquery/transformers/TransformerException.java
lib/src/main/java/io/cloudquery/transformers/TypeTransformer.java
lib/src/main/java/io/cloudquery/types/InetType.java
lib/src/main/java/io/cloudquery/types/JSONType.java
lib/src/main/java/io/cloudquery/types/ListType.java
lib/src/test/java/io/cloudquery/transformers/TypeTransformerTest.java
lib/src/test/java/io/cloudquery/types/ListTypeTest.java

Implementing tests for a type converter to convert types in a similar way to the current [Go implementation](https://github.com/cloudquery/plugin-sdk/blob/main/transformers/struct_test.go#L22-L52). 
* Some simple stubbed Arrow extension types needed to be added for `InetType` and `JSONType` - implementation to follow in future PRs. 
* A wrapper around the arrow `List` type was created to reproduce the `ListOf` functionality present in the Go arrow SDK but not in the Java.
fixes: #31

chore: adding type transformer

---

lib/src/main/java/io/cloudquery/scalar/DateDay.java
lib/src/main/java/io/cloudquery/scalar/DateMilli.java
lib/src/test/java/io/cloudquery/scalar/DateDayTest.java
lib/src/test/java/io/cloudquery/scalar/DateMilliTest.java

feat: Date scalars

---

lib/build.gradle
lib/src/main/java/io/cloudquery/schema/ClientMeta.java
lib/src/main/java/io/cloudquery/schema/Column.java
lib/src/main/java/io/cloudquery/schema/ColumnResolver.java
lib/src/main/java/io/cloudquery/schema/Resource.java
lib/src/main/java/io/cloudquery/transformers/ResolverTransformer.java
lib/src/main/java/io/cloudquery/transformers/TransformerException.java
lib/src/test/java/io/cloudquery/transformers/DefaultResolverTransformerTest.java

Adding the default implementation for the `ResolverTransformer` to set the value of a scalar based on a path lookup in the base resource item.
fixes: #32

chore: adding a resolver transformer

---

lib/src/main/java/io/cloudquery/scalar/Timestamp.java
lib/src/test/java/io/cloudquery/scalar/TimestampTest.java

feat: Scalar Timestamp

---

lib/src/main/java/io/cloudquery/transformers/IgnoreInTestsTransformer.java
lib/src/test/java/io/cloudquery/transformers/IgnoreInTestsTransformerTest.java

Java version of [DefaultIgnoreInTestsTransformer](https://github.com/cloudquery/plugin-sdk/blob/main/transformers/struct.go#L41-L45) 
fixes: #33

chore: add default implementation for `IgnoreInTestsTransformer` interface

---

lib/build.gradle
lib/src/main/java/io/cloudquery/scalar/UUID.java
lib/src/test/java/io/cloudquery/scalar/UUIDTest.java

NOTE: added an equals verify test which suggests overriding `hashcode` also
refs: #4
fixes: #52

chore: adding UUID scalar

---

lib/build.gradle
lib/src/main/java/io/cloudquery/types/UUIDType.java
lib/src/test/java/io/cloudquery/types/UUIDTypeTest.java

The Java arrow SDK doesn't appear to support the builder classes (structs) that Go does (unless I'm missing something). Instead you return a `FieldVector` from the extension type which is used to populate with values. The `FieldVector` instance is commonly based on the underlying storage type for the extension.
fixes: #57 
refs: #50

chore: adding UUID extension impl

---

lib/src/main/java/io/cloudquery/types/JSONType.java
lib/src/test/java/io/cloudquery/types/JSONTypeTest.java

chore: add support for arrow JSON extension

---

lib/build.gradle
lib/src/main/java/io/cloudquery/MainClass.java
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java
lib/src/main/java/io/cloudquery/schema/Column.java
lib/src/main/java/io/cloudquery/schema/Resource.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/main/java/io/cloudquery/server/ServeCommand.java
lib/src/test/java/io/cloudquery/schema/ResourceTest.java

~~Still doesn't work and I need to handle the options like include, skip, etc.~~
Got the gRPC call to work.
Had to:
1. Add `org.apache.arrow:arrow-memory-core` as implementation dependency
2. Add `org.apache.arrow:arrow-memory-nett` as runtime only dependency (see https://mvnrepository.com/artifact/org.apache.arrow/arrow-memory-netty/12.0.1)
3. Add another gradle task so the runtime class is loaded properly. We'll need see how this works with a published version of the SDK.

feat: Implement `getTables`

---

lib/build.gradle
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java

Follow up to https://github.com/cloudquery/plugin-sdk-java/pull/71.
Passes the options so users can filter tables

fix: Pass options to tables method

---

lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/plugin/BackendOptions.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/main/java/io/cloudquery/server/ServeCommand.java

First part of the sync, sending migrate table messages to the client

feat(sync): Send migrate messages

---

lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java

We need to flatten tables in the `getTables` call otherwise relations will not be migrated in `cloudquery migrate` (see https://github.com/cloudquery/plugin-sdk-python/pull/41)

fix: Flatten tables in getTables gRPC call

---

lib/build.gradle
lib/src/main/java/io/cloudquery/scalar/JSON.java
lib/src/test/java/io/cloudquery/scalar/JSONTest.java

feat: adding JSON scalar

---

lib/build.gradle

I removed this by mistake in https://github.com/cloudquery/plugin-sdk-java/pull/82

fix: Add `jackson-annotations` to `build.gradle`

---

lib/build.gradle
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/memdb/MemDBClient.java
lib/src/main/java/io/cloudquery/memdb/Spec.java
lib/src/main/java/io/cloudquery/memdb/Table1Data.java
lib/src/main/java/io/cloudquery/memdb/Table2Data.java
lib/src/main/java/io/cloudquery/plugin/ClientNotInitializedException.java
lib/src/main/java/io/cloudquery/plugin/NewClientOptions.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java
lib/src/main/java/io/cloudquery/plugin/TableOutputStream.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/scheduler/SchedulerTableOutputStream.java
lib/src/main/java/io/cloudquery/schema/ClientMeta.java
lib/src/main/java/io/cloudquery/schema/Resource.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/main/java/io/cloudquery/schema/TableResolver.java

Implemented `init` and some parts of resolving tables during sync.
To be done in future PRs:

feat(sync): Initial insert message support

---

lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/schema/Resource.java
lib/src/main/java/io/cloudquery/schema/Table.java

Working towards adding the write logic, which will need arrow decoding logic. This seems like a good point to create an Arrow helper class to contain the encoding and decoding steps.
refs: #85

refactor: moving arrow conversion methods into a helper class

---

lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/memdb/MemDBClient.java
lib/src/main/java/io/cloudquery/messages/WriteMessage.java
lib/src/main/java/io/cloudquery/messages/WriteMigrateTable.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java
lib/src/main/java/io/cloudquery/schema/ClientMeta.java
lib/src/test/java/io/cloudquery/helper/ArrowHelperTest.java
lib/src/test/java/io/cloudquery/internal/servers/plugin/v3/PluginServerTest.java

Adding support for the `MessageMigrateTable` requests
refs: #85

chore: adding supporting decode for write logic

---

lib/build.gradle
lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/memdb/Table1Data.java
lib/src/main/java/io/cloudquery/memdb/Table2Data.java
lib/src/main/java/io/cloudquery/plugin/SyncStream.java
lib/src/main/java/io/cloudquery/scalar/Scalar.java
lib/src/main/java/io/cloudquery/scalar/String.java
lib/src/main/java/io/cloudquery/scalar/Timestamp.java
lib/src/main/java/io/cloudquery/scheduler/OnResourceResolved.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/scheduler/SchedulerTableOutputStream.java
lib/src/main/java/io/cloudquery/schema/Column.java
lib/src/main/java/io/cloudquery/schema/Resource.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/main/java/io/cloudquery/transformers/Tables.java
lib/src/main/java/io/cloudquery/transformers/TypeTransformer.java
lib/src/main/java/io/cloudquery/types/JSONType.java
lib/src/main/java/io/cloudquery/types/UUIDType.java
lib/src/test/java/io/cloudquery/helper/ArrowHelperTest.java
lib/src/test/java/io/cloudquery/scalar/StringTest.java
lib/src/test/java/io/cloudquery/scalar/TimestampTest.java
lib/src/test/java/io/cloudquery/types/JSONTypeTest.java

Part of https://github.com/cloudquery/plugin-sdk-java/issues/5
~~Still doesn't work but at least Arrow doesn't throw an exception~~
Added column metadata too, and had to change some of the scalars/types to use whatever Java type the Arrow vector expects

feat: Encode resources with data

---

lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/schema/Table.java

Follow up to https://medium.com/@johnpang/optionals-and-lombok-a414639dca1e

refactor: Avoid casting, use Optional, use equals, use Boolean.toString

---

lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/memdb/Spec.java
lib/src/main/java/io/cloudquery/memdb/Table2ChildData.java
lib/src/main/java/io/cloudquery/scheduler/OnResourceResolved.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/scheduler/SchedulerTableOutputStream.java
lib/src/main/java/io/cloudquery/schema/Table.java

Fixes https://github.com/cloudquery/plugin-sdk-java/issues/5
~~Probably needs some cleanup~~

feat: Implement concurrency and relations resolving

---

.gitignore
lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/memdb/MemDBClient.java
lib/src/main/java/io/cloudquery/messages/WriteInsert.java
lib/src/main/java/io/cloudquery/scalar/Scalar.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/main/java/io/cloudquery/server/PluginServe.java
lib/src/main/java/io/cloudquery/types/Extensions.java
lib/src/main/java/io/cloudquery/types/UUIDType.java
lib/src/test/java/io/cloudquery/internal/servers/plugin/v3/PluginServerTest.java

chore: implment write insert logic

---

lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/scheduler/Scheduler.java
lib/src/main/java/io/cloudquery/schema/Resource.java
lib/src/test/java/io/cloudquery/schema/ResourceTest.java

Fixes https://github.com/cloudquery/plugin-sdk-java/issues/92

feat: Resolve CQId, add CQIds to MemDB plugin

---

lib/src/main/java/io/cloudquery/scalar/Timestamp.java
lib/src/test/java/io/cloudquery/scalar/TimestampTest.java

Switch to using a base storage of `ms` and consistent across all parsing methods

fix: make the underlying timestamp consistent

---

lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/memdb/Table1Data.java
lib/src/main/java/io/cloudquery/scalar/Scalar.java
lib/src/test/java/io/cloudquery/scalar/ScalarTest.java

As part of the bitbucket plugin work the JSON fields were not making it through to the destination. This was because the JSON type was assuming the underlying storage type of the extension instead e.g. Binary in the case of JSON.
Checking for extension type first will allow us to prefer our defined Arrow extensions over
the built-in types.

fix: check for extension type before built-in arrow types

---

lib/src/main/java/io/cloudquery/helper/ArrowHelper.java
lib/src/main/java/io/cloudquery/scalar/DateMilli.java
lib/src/main/java/io/cloudquery/scalar/Number.java
lib/src/main/java/io/cloudquery/transformers/TypeTransformer.java
lib/src/main/java/io/cloudquery/types/UUIDType.java
lib/src/test/java/io/cloudquery/helper/ArrowHelperTest.java
lib/src/test/java/io/cloudquery/transformers/TransformWithClassTest.java
lib/src/test/java/io/cloudquery/transformers/TypeTransformerTest.java

Follow-up for https://github.com/cloudquery/plugin-sdk-java/pull/141
Also notice https://github.com/apache/arrow/issues/38891

feat: Add better roundtrip support

---

lib/src/main/java/io/cloudquery/server/ServeCommand.java
lib/src/test/java/io/cloudquery/server/PluginServeTest.java

Otherwise plugins can't seem to be launched
https://github.com/cloudquery/plugin-pb-go/blob/cd22fa7ec57df5d7d1f5b3991d4910df8df93696/managedplugin/plugin.go#L388

fix: Use correct param name for `--no-sentry` (not `--disable-sentry`)

---

lib/src/main/java/io/cloudquery/server/ServeCommand.java

plugin-pb-go [1.15.0](https://github.com/cloudquery/plugin-pb-go/pull/196) now uses `--license` when invoking plugins, if one is set by the cli.

fix: Add --license placeholder for future use

---

lib/src/main/java/io/cloudquery/internal/servers/plugin/v3/PluginServer.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java
lib/src/test/java/io/cloudquery/internal/servers/plugin/v3/PluginServerTest.java

Closes https://github.com/cloudquery/cloudquery/issues/16503

feat: Implement `GetSpecSchema`

---

.github/workflows/ci.yml
.gitignore
Dockerfile
docs/overview.md
lib/build.gradle
lib/src/main/java/io/cloudquery/memdb/MemDB.java
lib/src/main/java/io/cloudquery/plugin/BuildArch.java
lib/src/main/java/io/cloudquery/plugin/BuildOS.java
lib/src/main/java/io/cloudquery/plugin/BuildTarget.java
lib/src/main/java/io/cloudquery/plugin/Plugin.java
lib/src/main/java/io/cloudquery/plugin/PluginKind.java
lib/src/main/java/io/cloudquery/schema/Table.java
lib/src/main/java/io/cloudquery/server/PackageCommand.java
lib/src/main/java/io/cloudquery/server/PackageJson.java
lib/src/main/java/io/cloudquery/server/PluginServe.java
lib/src/main/java/io/cloudquery/server/SupportedTargetJson.java
lib/src/main/java/io/cloudquery/server/TablesJson.java
lib/src/test/java/io/cloudquery/server/PluginPackageTest.java

Fixes https://github.com/cloudquery/cloudquery-issues/issues/790

feat: Add package command

---

lib/src/main/java/io/cloudquery/memdb/MemDB.java

I noticed the [table list for Bitbucket plugin is broken in the Hub](https://hub.cloudquery.io/plugins/source/cloudquery/bitbucket/latest/tables). The reason is that we don't call `setParents` thus publish all tables as top level ones. The UI then tries to render items with duplicate keys and fails.
This PR fixes the MemDB plugin in the SDK which is used as a reference for other plugins. I'll fix the Bitbucket plugin in a separate PR.
There might be a better way to implicitly initialize the parents but I don't we should spend more time on it

fix: Call setParents on `MemDB` tables

---

.github/workflows/ci.yml

The action we were using is deprecated https://github.com/gradle/wrapper-validation-action

chore: Use non deprecated action
